
server-name: "Velocity"

channels:
  # These are the channels that players can join and chat in
  # The first one listed is the default channel when a player joins the server
  local:
    name: "本地"
    type: LOCAL
    # Messages from players in these servers will NOT be sent to the backend
    # but they will directly be handled by this plugin on the proxy level
    force-handle-servers:
      - "server1"
      - "server2"
    format: "&f<%player%> &r" # This prefix will only be used if chat is processed on this plugin
    commands:
      - local
      - l
  global:
    name: "跨服"
    type: GLOBAL
    format: "<#47BFFB>[跨服] &8[&f%player%&8]&f " # This is the prefix of the message sent to the global channel
    # Player is not allowed in this channel when in these servers (any chat message will be blocked!)
    restricted-servers:
      - "server1"
    commands:
      - global
      - g
    prefixes:
      - "!"
  crossserver:
    name: "世界"
    type: REDIS
    format: "<#47fbeb>[世界] %server% &8[&f%player%&8]&f "
    redis-address: "0.0.0.0"
    redis-port:  6379
#   redis-user: "admin"
#   redis-password: "123456"
    commands:
      - crossserver
      - cs

  # Note that type ROOM is a bit special: only one channel can be specified as the ROOM channel!
  # Players can use the /room command to switch to the ROOM channel and chat with others with the same room code
  room:
    name: "房间"
    type: ROOM
    format: "<#ff6600>[房间 %room_code%] &8[&f%player%&8] &f"
    commands:
      - room

message: # /msg
  format-inbound: '<#47BFFB>%name% &8→ <#47BFFB>你&8: '
  format-outbound: '<#47BFFB>你 &8→ <#47BFFB>%name%&8: '
  message-command:
    - msg
  reply-command:
    - reply
    - r

module:
  mention:
    bossbar-progress-decrease: 0.05 # 0-1, usually 0.05 is fine
    sound-effect-id: "minecraft:entity.experience_orb.pickup"
    sound-effect-volume: 1 # 0-1
    sound-effect-pitch: 1 # 0.5-2