# Server group name displayed in cross-server channels. Must be unique.
# If you wish to use redis, YOU MUST CHANGE THIS TO SOMETHING ELSE
server-name: "Velocity"

lang: "en-US"

# Players on the following servers will not have their chat messages processed by this plugin when "passthrough" option is enabled!
# Suitable for cases where a sub-server uses its own independent chat plugin
unhandled-servers:
  - "server1"
  - "server2"

database:
  type: "sqlite" # SQLITE / MYSQL

  database: "minecraft"
  host: "0.0.0.0"
  port: 3306

  username: ""
  password: ""


redis:
  enabled: false
  address: "0.0.0.0"
  port:  6379
#  user: "admin"
#  password: "123456"

message: # /msg
  format-inbound: '<#47BFFB>%name% &8→ <#47BFFB>You&8: '
  format-outbound: '<#47BFFB>You &8→ <#47BFFB>%name%&8: '
  format-third-party: '<#47BFFB>%sender% &8→ <#47BFFB>%receiver%&8: '
  message-command:
    - msg
  reply-command:
    - reply
    - r

chat-history:
  message-per-page: 10

module:
  mention:
    bossbar-progress-decrease: 0.05 # 0-1, generally 0.05 is sufficient
    sound-effect-id: "minecraft:entity.experience_orb.pickup"
    sound-effect-volume: 1 # 0-1
    sound-effect-pitch: 1 # 0.5-2
