channels:
  local:
    name: "&e本地"
    type: LOCAL
    # Messages from players in these servers will NOT be sent to the backend
    # but they will directly be handled by this plugin on the proxy level
    force-handle-servers:
      - "server1"
      - "server2"
    format: "&f<%player%> &r" # This prefix will only be used if chat is processed on this plugin
    commands:
      - local
      - l
  global:
    name: "&a全局"
    type: GLOBAL
    format: "&a[全局]&7[&f%player%&7] &r" # This is the prefix of the message sent to the global channel
    commands:
      - global
      - g
    prefixes:
      - "!"
  crossserver:
    name: "&b跨服"
    type: REDIS
    format: "&b[跨服]&7[&f%player%&7] &r"
    redis-address: "0.0.0.0"
    redis-port:  6379
#   redis-user: "admin"
#   redis-password: "123456"
    commands:
      - crossserver
      - cs

  # Note that type ROOM is a bit special: only one channel can be specified as the ROOM channel!
  # Players can use the /room command to switch to the ROOM channel and chat with others with the same room code
  room:
    name: "房间"
    type: ROOM
    format: "&c[房间 %room_code%]&7[&f%player%&7] &r"
    commands:
      - room


module:
  mention:
    bossbar-progress-decrease: 0.05 # 0-1, usually 0.05 is fine
    sound-effect-id: "minecraft:entity.experience_orb.pickup"
    sound-effect-volume: 1 # 0-1
    sound-effect-pitch: 1 # 0.5-2